POST http://localhost:4000/api/v1/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "ivan",
    "username": "vinoivan",
    "email": "ivanvino@gmail.com",
    "password": "card1234"
}

###
POST http://localhost:4000/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "ivanvino@gmail.com",
    "password": "card1234"
}

###
POST http://localhost:4000/api/v1/auth/verify HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZjUzYTI4Y2U0YjRmYTVmZDUzY2Y2OSIsImVtYWlsIjoiaXZhbnZpbm9AZ21haWwuY29tIiwidXNlcm5hbWUiOiJ2aW5vaXZhbiIsImlhdCI6MTc0NDE1MTg0NiwiZXhwIjoxNzQ0MTU1NDQ2fQ.DAsxjhCdQU-nJWNR7EjRVvaGC5yY0JPxM1jnJPH7cFs